# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- main

pool:
  vmImage: ubuntu-latest



steps:



- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d -v github.com/Azure-Samples/openhack-devops-team/...'
    workingDirectory: '$(System.DefaultWorkingDirectory)/apis/trips'
    
- task: Go@0
  inputs:
    command: 'build'
    arguments: '-d -v github.com/Azure-Samples/openhack-devops-team/...'
    workingDirectory: '$(System.DefaultWorkingDirectory)/apis/trips'